# Generated by Django 5.2.7 on 2026-10-02 21:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('internest_core', '0005_email_verification'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry', models.CharField(choices=[('software', 'Software & SaaS'), ('fintech', 'Fintech'), ('ecommerce', 'E-commerce & Retail'), ('edtech', 'Education'), ('healthtech', 'Health'), ('marketing', 'Marketing & Media'), ('logistics', 'Logistics & Mobility'), ('other', 'Other')], max_length=20)),
                ('founded_year', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(2100)])),
                ('description', models.TextField(max_length=1000)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('partner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_profile', to='internest_core.partnerprofile')),
            ],
            options={
                'verbose_name': 'Company profile',
                'verbose_name_plural': 'Company profiles',
            },
        ),
        migrations.CreateModel(
            name='PendingCompanyProfile',
            fields=[
            ],
            options={
                'verbose_name': 'Pending verification',
                'verbose_name_plural': '⏳ Pending verification',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('internest_startups.companyprofile',),
        ),
    ]
