# Generated by Django 5.2.7 on 2026-10-03 21:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


def seed_promo_codes(apps, schema_editor):
    import datetime
    PromoCode = apps.get_model("internest_startups", "PromoCode")
    PromoCode.objects.get_or_create(code="STARTUP50", defaults={"discount_percent": 50, "max_uses": 100})
    PromoCode.objects.get_or_create(code="EGYPT2026", defaults={"discount_percent": 20, "valid_until": datetime.date(2026, 12, 31)})


class Migration(migrations.Migration):

    dependencies = [
        ('internest_core', '0005_email_verification'),
        ('internest_startups', '0002_companyprofile_founder_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('discount_percent', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('is_active', models.BooleanField(default=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('max_uses', models.PositiveIntegerField(blank=True, null=True)),
                ('times_used', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ProUpgradeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('months', models.PositiveSmallIntegerField(default=1)),
                ('list_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('discount_percent', models.PositiveSmallIntegerField(default=0)),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('pending', 'Awaiting payment'), ('activated', 'Activated'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pro_requests', to='internest_core.partnerprofile')),
                ('promo_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='internest_startups.promocode')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RunPython(seed_promo_codes, migrations.RunPython.noop),
    ]
