# Generated by Django 5.2.7 on 2026-10-03 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internest_startups', '0003_pro_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='identity_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='previous_company_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
