# Generated by Django 5.2.7 on 2026-10-09 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internest_core', '0009_talent_pool_opt_in'),
        ('internest_startups', '0004_identity_change_tracking'),
    ]

    operations = [
        migrations.CreateModel(
            name='TalentInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('internship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talent_invitations', to='internest_core.internship')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talent_invitations', to='internest_core.partnerprofile')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talent_invitations', to='internest_core.studentprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('internship', 'student'), name='unique_talent_invitation')],
            },
        ),
    ]
