# Generated by Django 5.2.7 on 2026-10-10 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internest_startups', '0006_invitation_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='proupgraderequest',
            name='country',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
        migrations.AddField(
            model_name='proupgraderequest',
            name='currency',
            field=models.CharField(default='USD', max_length=3),  # requests made before this were priced in USD
        ),
        migrations.AlterField(
            model_name='proupgraderequest',
            name='currency',
            field=models.CharField(default='EGP', max_length=3),
        ),
        migrations.AddField(
            model_name='proupgraderequest',
            name='gateway',
            field=models.CharField(default='manual', max_length=20),
        ),
    ]
