# Generated by Django 5.2.7 on 2026-10-02 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('internest_core', '0005_email_verification'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoungePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('body', models.TextField(max_length=5000)),
                ('category', models.CharField(blank=True, choices=[('hiring', '#Hiring'), ('advice', '#Advice'), ('b2b', '#B2B_Partnership')], max_length=10)),
                ('body_fingerprint', models.CharField(db_index=True, editable=False, max_length=64)),
                ('visibility', models.CharField(choices=[('visible', 'Visible'), ('hidden', 'Hidden pending review'), ('removed', 'Removed by admin')], db_index=True, default='visible', max_length=10)),
                ('hidden_reason', models.CharField(blank=True, choices=[('', '—'), ('link_spam', 'Suspicious link'), ('duplicate', 'Duplicate text'), ('flags', 'Flagged by founders')], max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lounge_posts', to='internest_core.partnerprofile')),
                ('upvoters', models.ManyToManyField(blank=True, related_name='upvoted_lounge_posts', to='internest_core.partnerprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoungeComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=2000)),
                ('visibility', models.CharField(choices=[('visible', 'Visible'), ('hidden', 'Hidden pending review'), ('removed', 'Removed by admin')], default='visible', max_length=10)),
                ('hidden_reason', models.CharField(blank=True, choices=[('', '—'), ('link_spam', 'Suspicious link'), ('duplicate', 'Duplicate text'), ('flags', 'Flagged by founders')], max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lounge_comments', to='internest_core.partnerprofile')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='internest_lounge.loungecomment')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='internest_lounge.loungepost')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoungeFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lounge_flags', to='internest_core.partnerprofile')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='internest_lounge.loungepost')),
            ],
            options={
                'unique_together': {('post', 'reporter')},
            },
        ),
    ]
