# Generated by Django 5.2.7 on 2026-10-03 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internest_lounge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loungepost',
            name='title',
            field=models.CharField(blank=True, max_length=160),
        ),
    ]
