# Generated by Django 5.2.7 on 2026-09-24 11:46

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('internest_core', '0005_email_verification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('discipline', models.CharField(choices=[('computing', 'Computer Science & IT'), ('business', 'Business & Finance'), ('media', 'Media & Design'), ('law', 'Law'), ('engineering', 'Engineering'), ('health', 'Health Sciences'), ('general', 'Transferable / Soft Skills')], max_length=20)),
                ('aliases', models.TextField(blank=True, help_text='Comma-separated terms (any language) that explicitly name this skill in a CV.')),
                ('implicit_signals', models.TextField(blank=True, help_text='Comma-separated phrases that imply this skill from projects / work history.')),
                ('challenge_length', models.PositiveSmallIntegerField(default=8, validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(30)])),
                ('pass_threshold', models.PositiveSmallIntegerField(default=70, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['discipline', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EmployerSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('free', 'Free'), ('pro', 'Internest Pro')], default='free', max_length=10)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('partner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='internest_core.partnerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='SkillProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkedin_url', models.URLField(blank=True)),
                ('last_extracted_at', models.DateTimeField(blank=True, null=True)),
                ('extraction_count_today', models.PositiveSmallIntegerField(default=0)),
                ('extraction_day', models.DateField(blank=True, null=True)),
                ('partner_university', models.ForeignKey(blank=True, help_text="Academic partner allowed to view this student's skill analytics.", limit_choices_to={'is_academic': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affiliated_skill_profiles', to='internest_core.partnerprofile')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='skill_profile', to='internest_core.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='StudentSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('explicit', 'Explicit'), ('implicit', 'Implicit (inferred)')], max_length=10)),
                ('evidence', models.CharField(blank=True, max_length=300)),
                ('status', models.CharField(choices=[('claimed', 'Claimed'), ('verified', 'Verified'), ('lag', 'Skill lag detected')], default='claimed', max_length=10)),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('percentile', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('lag_sub_skills', models.JSONField(blank=True, default=list)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('cooldown_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_skills', to='internest_skills.skill')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='internest_core.studentprofile')),
            ],
            options={
                'ordering': ['-status', 'skill__name'],
                'unique_together': {('student', 'skill')},
            },
        ),
        migrations.CreateModel(
            name='ChallengeAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('item_ids', models.JSONField(default=list)),
                ('current_index', models.PositiveSmallIntegerField(default=0)),
                ('current_served_at', models.DateTimeField(blank=True, null=True)),
                ('state', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('terminated', 'Terminated (integrity)')], default='active', max_length=12)),
                ('focus_warnings', models.PositiveSmallIntegerField(default=0)),
                ('integrity_events', models.JSONField(blank=True, default=list)),
                ('termination_reason', models.CharField(blank=True, max_length=120)),
                ('score_pct', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('sub_skill_breakdown', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('student_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='internest_skills.studentskill')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='SubSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('keywords', models.TextField(blank=True, help_text='Comma-separated search terms used to match courses.')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_skills', to='internest_skills.skill')),
            ],
            options={
                'ordering': ['skill', 'name'],
                'unique_together': {('skill', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ExternalCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('provider', models.CharField(choices=[('Coursera', 'Coursera'), ('edX', 'edX'), ('Udemy', 'Udemy'), ('YouTube', 'YouTube'), ('Other', 'Other')], max_length=20)),
                ('url', models.URLField()),
                ('expected_outcome', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('sub_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_courses', to='internest_skills.subskill')),
            ],
        ),
        migrations.CreateModel(
            name='ChallengeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('mcq', 'Multiple choice'), ('case', 'Short case / written answer')], default='mcq', max_length=10)),
                ('prompt', models.TextField()),
                ('choices', models.JSONField(blank=True, default=list, help_text='MCQ only: ["option A", "option B", ...]')),
                ('correct_index', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('rubric', models.JSONField(blank=True, default=list, help_text='Case only: list of concept groups; each group is a list of accepted terms, e.g. [["npv","net present value"],["discount"]].')),
                ('time_limit_seconds', models.PositiveSmallIntegerField(default=45, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(60)])),
                ('weight', models.PositiveSmallIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='internest_skills.skill')),
                ('sub_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='internest_skills.subskill')),
            ],
        ),
        migrations.CreateModel(
            name='ChallengeResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(blank=True)),
                ('choice_index', models.SmallIntegerField(blank=True, null=True)),
                ('credit', models.FloatField(default=0.0)),
                ('elapsed_ms', models.PositiveIntegerField(default=0)),
                ('timed_out', models.BooleanField(default=False)),
                ('typing_stats', models.JSONField(blank=True, default=dict)),
                ('integrity_flags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='internest_skills.challengeattempt')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internest_skills.challengeitem')),
            ],
            options={
                'unique_together': {('attempt', 'item')},
            },
        ),
    ]
