# Generated by Django 5.2.7 on 2026-09-24 20:03

import django.core.validators
from django.db import migrations, models


def bump_challenge_length(apps, schema_editor):
    apps.get_model("internest_skills", "Skill").objects.filter(challenge_length=8).update(challenge_length=10)


class Migration(migrations.Migration):

    dependencies = [
        ('internest_skills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengeattempt',
            name='improvement_topics',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='challengeitem',
            name='code_snippet',
            field=models.TextField(blank=True, help_text='Optional code shown under the question (technical skills).'),
        ),
        migrations.AddField(
            model_name='challengeitem',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=6),
        ),
        migrations.AddField(
            model_name='challengeitem',
            name='topic',
            field=models.CharField(blank=True, help_text='Specific concept tested; used for improvement feedback.', max_length=160),
        ),
        migrations.AlterField(
            model_name='skill',
            name='challenge_length',
            field=models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(30)]),
        ),
        migrations.RunPython(bump_challenge_length, migrations.RunPython.noop),
    ]
