# Generated by Django 5.2.7 on 2026-10-02 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internest_core', '0005_email_verification'),
        ('internest_skills', '0002_quiz_difficulty_code_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='opportunities',
            field=models.ManyToManyField(blank=True, related_name='required_skills', to='internest_core.internship'),
        ),
        migrations.AddField(
            model_name='skill',
            name='opportunity_submissions',
            field=models.ManyToManyField(blank=True, related_name='required_skills', to='internest_core.partnerinternshipsubmission'),
        ),
    ]
