# Generated by Django 5.2.7 on 2026-10-08 16:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


SEED = [
    ("Graphic Design", "UI/UX Design", 0.6), ("Graphic Design", "Video Editing", 0.4),
    ("UI/UX Design", "Web Development", 0.4), ("Web Development", "Python", 0.35),
    ("SQL", "Python", 0.4), ("SQL", "Excel", 0.4), ("Financial Analysis", "Excel", 0.6),
    ("Digital Marketing", "Business Communication", 0.35), ("Legal Research", "Contract Drafting", 0.6),
    ("Project Management", "Business Communication", 0.4),
]


def seed_relations(apps, schema_editor):
    Skill = apps.get_model("internest_skills", "Skill")
    Relation = apps.get_model("internest_skills", "SkillRelation")
    by_name = {s.name.lower(): s for s in Skill.objects.all()}
    for a, b, w in SEED:
        sa, sb = by_name.get(a.lower()), by_name.get(b.lower())
        if sa and sb:
            Relation.objects.update_or_create(skill=sa, related=sb, defaults={"weight": w, "source": "seed"})


class Migration(migrations.Migration):

    dependencies = [
        ('internest_skills', '0003_opportunity_required_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='relations_refreshed_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.CreateModel(
            name='SkillRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('source', models.CharField(choices=[('seed', 'Seed'), ('ai', 'AI'), ('admin', 'Admin')], default='admin', max_length=10)),
                ('related', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_in', to='internest_skills.skill')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_out', to='internest_skills.skill')),
            ],
            options={
                'unique_together': {('skill', 'related')},
            },
        ),
        migrations.RunPython(seed_relations, migrations.RunPython.noop),
    ]
