# Generated by Django 5.2.7 on 2026-10-09 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internest_core', '0010_talent_pool_indexes'),
        ('internest_skills', '0005_ten_question_challenges'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='studentskill',
            index=models.Index(fields=['status', 'student'], name='studentskill_status_idx'),
        ),
        migrations.AddIndex(
            model_name='studentskill',
            index=models.Index(fields=['score', 'student'], name='studentskill_score_idx'),
        ),
    ]
