# Generated by Django 5.2.7 on 2026-10-02 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('internest_core', '0005_email_verification'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampusDemandVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_name', models.CharField(max_length=150)),
                ('faculty_name', models.CharField(max_length=150)),
                ('department', models.CharField(blank=True, max_length=150)),
                ('student_number', models.CharField(max_length=30, verbose_name='Student ID')),
                ('university_key', models.CharField(db_index=True, editable=False, max_length=150)),
                ('campus_key', models.CharField(db_index=True, editable=False, max_length=310)),
                ('referral_code', models.CharField(editable=False, max_length=16, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('referred_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='internest_campus.campusdemandvote')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campus_votes', to='internest_core.studentprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('student', 'university_key'), name='one_vote_per_user_per_university'), models.UniqueConstraint(fields=('student_number', 'university_key'), name='one_vote_per_student_id_per_university')],
            },
        ),
    ]
