# Generated by Django 5.2.7 on 2025-11-10 13:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('required_majors', models.CharField(max_length=255)),
                ('deadline', models.DateField()),
                ('is_premium', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PartnerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, unique=True, verbose_name='اسم الشركة/الجهة')),
                ('partner_code', models.CharField(help_text='الكود السري للدخول المخصص.', max_length=50, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='partner_logos/', verbose_name='شعار الشركة/الجهة')),
                ('is_academic', models.BooleanField(default=False, verbose_name='هل هي جهة أكاديمية؟')),
                ('official_website', models.URLField(blank=True, null=True, verbose_name='الموقع الرسمي')),
                ('official_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني الرسمي')),
                ('official_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم التواصل الرسمي')),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('twitter_url', models.URLField(blank=True, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('contract_expiry_date', models.DateField(blank=True, null=True, verbose_name='تاريخ انتهاء التعاقد (يحددها الأدمن)')),
                ('is_fully_verified', models.BooleanField(default=False, verbose_name='حساب موثوق (علامة الصح الزرقاء)')),
                ('profile_completion_score', models.IntegerField(default=0, verbose_name='نسبة الإكمال (%)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PartnerInternshipSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('required_majors', models.CharField(max_length=255)),
                ('deadline', models.DateField()),
                ('status', models.CharField(choices=[('Pending', 'قيد المراجعة'), ('Approved', 'تمت الموافقة'), ('Rejected', 'تم الرفض')], default='Pending', max_length=10)),
                ('submission_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internest_core.partnerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='PartnerCourseSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(help_text='وصف تفصيلي للكورس.')),
                ('price', models.DecimalField(decimal_places=2, help_text='سعر الكورس (لأغراض الإيرادات).', max_digits=6)),
                ('instructor_name', models.CharField(help_text='اسم مقدم الكورس.', max_length=100)),
                ('video_link', models.URLField(blank=True, help_text='رابط ترويجي/صورة/فيديو للكورس.', null=True)),
                ('points_awarded', models.IntegerField(help_text='نقاط Gamification عند إكمال الطالب للكورس.')),
                ('status', models.CharField(choices=[('Pending', 'قيد المراجعة'), ('Approved', 'تمت الموافقة'), ('Rejected', 'تم الرفض')], default='Pending', max_length=10)),
                ('submission_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internest_core.partnerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(blank=True, max_length=100, null=True, verbose_name='الجامعة')),
                ('major', models.CharField(blank=True, max_length=100, null=True, verbose_name='التخصص')),
                ('study_level', models.CharField(blank=True, choices=[('1', 'سنة أولى'), ('2', 'سنة ثانية'), ('3', 'سنة ثالثة'), ('4', 'سنة رابعة/خريج')], max_length=50, null=True, verbose_name='المستوى الدراسي')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الهاتف')),
                ('cv_file', models.FileField(blank=True, null=True, upload_to='cvs/', verbose_name='ملف السيرة الذاتية (CV)')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/', verbose_name='صورة الملف الشخصي')),
                ('linkedin_url', models.URLField(blank=True, null=True, verbose_name='رابط LinkedIn')),
                ('profile_completion_score', models.IntegerField(default=0, verbose_name='نسبة الإكمال (%)')),
                ('gamification_score', models.IntegerField(default=0, verbose_name='نقاط الأداء')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('قيد المراجعة', 'قيد المراجعة'), ('مقبول', 'مقبول'), ('مرفوض', 'مرفوض')], default='قيد المراجعة', max_length=50)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('internship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internest_core.internship')),
            ],
            options={
                'unique_together': {('internship', 'applicant')},
            },
        ),
    ]
