# Generated by Django 5.2.7 on 2025-11-27 16:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='الكود')),
                ('discount_percentage', models.PositiveIntegerField(help_text='رقم من 1 إلى 100', verbose_name='نسبة الخصم (%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال؟')),
            ],
            options={
                'verbose_name': 'كود خصم',
                'verbose_name_plural': '🏷️ أكواد الخصم',
            },
        ),
        migrations.CreateModel(
            name='GamificationTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان التاسك')),
                ('description', models.TextField(verbose_name='وصف التاسك')),
                ('points_awarded', models.IntegerField(default=10, verbose_name='النقاط الممنوحة')),
                ('is_active', models.BooleanField(default=True, verbose_name='متاح للطلاب؟')),
            ],
            options={
                'verbose_name': 'مهمة (تاسك)',
                'verbose_name_plural': '🎯 المهام (التاسكات)',
            },
        ),
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('required_majors', models.CharField(max_length=255)),
                ('deadline', models.DateField()),
                ('is_premium', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('قيد المراجعة', 'قيد المراجعة'), ('محول للشريك', 'محول للشريك'), ('مرفوض', 'مرفوض')], default='قيد المراجعة', max_length=50)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('internship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internest_core.internship')),
            ],
            options={
                'unique_together': {('internship', 'applicant')},
            },
        ),
        migrations.CreateModel(
            name='PartnerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, unique=True, verbose_name='اسم الشركة/الجهة')),
                ('partner_code', models.CharField(help_text='الكود السري للدخول المخصص.', max_length=50, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='partner_logos/', verbose_name='شعار الشركة/الجهة')),
                ('is_academic', models.BooleanField(default=False, verbose_name='هل هي جهة أكاديمية؟')),
                ('official_website', models.URLField(blank=True, null=True, verbose_name='الموقع الرسمي')),
                ('official_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني الرسمي')),
                ('official_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم التواصل الرسمي')),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('twitter_url', models.URLField(blank=True, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('contract_expiry_date', models.DateField(blank=True, null=True, verbose_name='تاريخ انتهاء التعاقد (يحددها الأدمن)')),
                ('is_fully_verified', models.BooleanField(default=False, verbose_name='حساب موثوق (علامة الصح الزرقاء)')),
                ('profile_completion_score', models.IntegerField(default=0, verbose_name='نسبة الإكمال (%)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PartnerInternshipSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('duration', models.CharField(max_length=50, verbose_name='مدة التدريب')),
                ('location', models.CharField(max_length=100)),
                ('required_majors', models.CharField(max_length=255)),
                ('deadline', models.DateField()),
                ('status', models.CharField(choices=[('Pending', 'قيد المراجعة'), ('Approved', 'تمت الموافقة'), ('Rejected', 'تم الرفض')], default='Pending', max_length=10)),
                ('submission_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internest_core.partnerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='PartnerCourseSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(help_text='وصف تفصيلي للكورس.')),
                ('price', models.DecimalField(decimal_places=2, help_text='سعر الكورس (لأغراض الإيرادات).', max_digits=6)),
                ('instructor_name', models.CharField(help_text='اسم مقدم الكورس.', max_length=100)),
                ('video_link', models.URLField(blank=True, help_text='رابط ترويجي/صورة/فيديو للكورس.', null=True)),
                ('points_awarded', models.IntegerField(help_text='نقاط Gamification عند إكمال الطالب للكورس.')),
                ('status', models.CharField(choices=[('Pending', 'قيد المراجعة'), ('Approved', 'تمت الموافقة'), ('Rejected', 'تم الرفض')], default='Pending', max_length=10)),
                ('submission_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internest_core.partnerprofile')),
            ],
        ),
        migrations.AddField(
            model_name='internship',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internships', to='internest_core.partnerprofile', verbose_name='الشريك (الشركة)'),
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(blank=True, max_length=100, null=True, verbose_name='الجامعة')),
                ('major', models.CharField(blank=True, max_length=100, null=True, verbose_name='التخصص')),
                ('study_level', models.CharField(blank=True, choices=[('1', 'سنة أولى'), ('2', 'سنة ثانية'), ('3', 'سنة ثالثة'), ('4', 'سنة رابعة/خريج')], max_length=50, null=True, verbose_name='المستوى الدراسي')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الهاتف')),
                ('cv_file', models.FileField(blank=True, null=True, upload_to='cvs/', verbose_name='ملف السيرة الذاتية (CV)')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/', verbose_name='صورة الملف الشخصي')),
                ('linkedin_url', models.URLField(blank=True, null=True, verbose_name='رابط LinkedIn')),
                ('profile_completion_score', models.IntegerField(default=0, verbose_name='نسبة الإكمال (%)')),
                ('gamification_score', models.IntegerField(default=0, verbose_name='نقاط الأداء')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GoldenListStudent',
            fields=[
            ],
            options={
                'verbose_name': 'طالب في الجولدن ليست',
                'verbose_name_plural': '🏆 الجولدن ليست (أعلى الطلاب)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('internest_core.studentprofile',),
        ),
        migrations.CreateModel(
            name='TaskQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='نص السؤال')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='internest_core.gamificationtask', verbose_name='التاسك التابع له')),
            ],
            options={
                'verbose_name': 'سؤال',
                'verbose_name_plural': 'الأسئلة',
            },
        ),
        migrations.CreateModel(
            name='TaskAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='نص الإجابة (الاختيار)')),
                ('is_correct', models.BooleanField(default=False, verbose_name='هل هذه هي الإجابة الصحيحة؟')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='internest_core.taskquestion', verbose_name='السؤال التابع له')),
            ],
            options={
                'verbose_name': 'اختيار (إجابة)',
                'verbose_name_plural': 'الاختيارات (الإجابات)',
            },
        ),
        migrations.CreateModel(
            name='StudentEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_on', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التسجيل')),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='السعر المدفوع')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='internest_core.partnercoursesubmission', verbose_name='الكورس')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_courses', to='internest_core.studentprofile', verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'تسجيل (كورس)',
                'verbose_name_plural': '🧑\u200d🎓 تسجيلات الطلاب في الكورسات',
                'unique_together': {('student', 'course')},
            },
        ),
        migrations.CreateModel(
            name='PartnerApplicantData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forwarded_on', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإرسال')),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='internest_core.application', verbose_name='الطلب الأصلي')),
                ('internship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internest_core.internship', verbose_name='للتدريب')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_applicants', to='internest_core.partnerprofile', verbose_name='الشريك المستقبل')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internest_core.studentprofile', verbose_name='ملف الطالب')),
            ],
            options={
                'verbose_name': 'ملف متقدم مُرسل للشريك',
                'verbose_name_plural': 'ملفات المتقدمين المُرسلة',
                'unique_together': {('partner', 'student', 'internship')},
            },
        ),
        migrations.CreateModel(
            name='StudentTaskRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_on', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_records', to='internest_core.studentprofile')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='internest_core.gamificationtask')),
            ],
            options={
                'verbose_name': 'سجل إكمال مهمة',
                'verbose_name_plural': 'سجلات إكمال المهام',
                'unique_together': {('student', 'task')},
            },
        ),
    ]
