# Generated by Django 5.2.7 on 2025-11-10 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internest_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoldenListStudent',
            fields=[
            ],
            options={
                'verbose_name': 'طالب في الجولدن ليست',
                'verbose_name_plural': '🏆 الجولدن ليست (أعلى الطلاب)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('internest_core.studentprofile',),
        ),
        migrations.RemoveField(
            model_name='internship',
            name='company_name',
        ),
        migrations.AddField(
            model_name='internship',
            name='partner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='internships', to='internest_core.partnerprofile', verbose_name='الشريك (الشركة)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('قيد المراجعة', 'قيد المراجعة'), ('محول للشريك', 'محول للشريك'), ('مرفوض', 'مرفوض')], default='قيد المراجعة', max_length=50),
        ),
        migrations.CreateModel(
            name='PartnerApplicantData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forwarded_on', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإرسال')),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='internest_core.application', verbose_name='الطلب الأصلي')),
                ('internship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internest_core.internship', verbose_name='للتدريب')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_applicants', to='internest_core.partnerprofile', verbose_name='الشريك المستقبل')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internest_core.studentprofile', verbose_name='ملف الطالب')),
            ],
            options={
                'verbose_name': 'ملف متقدم مُرسل للشريك',
                'verbose_name_plural': 'ملفات المتقدمين المُرسلة',
                'unique_together': {('partner', 'student', 'internship')},
            },
        ),
    ]
