# Generated by Django 5.2.7 on 2025-11-27 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internest_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerinternshipsubmission',
            name='duration',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='مدة التدريب'),
        ),
    ]
