# Generated by Django 5.2.7 on 2025-11-27 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internest_core', '0002_alter_partnerinternshipsubmission_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='personal_email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='البريد الإلكتروني الشخصي'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='university_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني الجامعي'),
        ),
    ]
