# Generated by Django 5.2.7 on 2025-11-10 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internest_core', '0002_goldenliststudent_remove_internship_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerprofile',
            name='pending_profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='partner_pending_pics/', verbose_name='الصورة المعلقة للمراجعة'),
        ),
        migrations.AddField(
            model_name='partnerprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='partner_profile_pics/', verbose_name='صورة البروفايل (الموافق عليها)'),
        ),
        migrations.AddField(
            model_name='partnerprofile',
            name='profile_picture_status',
            field=models.CharField(choices=[('None', 'لا توجد'), ('Pending', 'قيد المراجعة'), ('Approved', 'موافق عليها'), ('Rejected', 'مرفوضة')], default='None', max_length=10, verbose_name='حالة صورة البروفايل'),
        ),
    ]
