# Generated by Django 5.2.7 on 2025-11-10 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internest_core', '0003_partnerprofile_pending_profile_picture_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnerprofile',
            name='pending_profile_picture',
        ),
        migrations.RemoveField(
            model_name='partnerprofile',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='partnerprofile',
            name='profile_picture_status',
        ),
    ]
