# Generated by Django 5.2.7 on 2025-11-10 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internest_core', '0004_remove_partnerprofile_pending_profile_picture_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GamificationTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان التاسك')),
                ('description', models.TextField(verbose_name='وصف التاسك')),
                ('points_awarded', models.IntegerField(default=10, verbose_name='النقاط الممنوحة')),
                ('is_active', models.BooleanField(default=True, verbose_name='متاح للطلاب؟')),
            ],
            options={
                'verbose_name': 'مهمة (تاسك)',
                'verbose_name_plural': '🎯 المهام (التاسكات)',
            },
        ),
        migrations.CreateModel(
            name='TaskQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='نص السؤال')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='internest_core.gamificationtask', verbose_name='التاسك التابع له')),
            ],
            options={
                'verbose_name': 'سؤال',
                'verbose_name_plural': 'الأسئلة',
            },
        ),
        migrations.CreateModel(
            name='TaskAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='نص الإجابة (الاختيار)')),
                ('is_correct', models.BooleanField(default=False, verbose_name='هل هذه هي الإجابة الصحيحة؟')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='internest_core.taskquestion', verbose_name='السؤال التابع له')),
            ],
            options={
                'verbose_name': 'اختيار (إجابة)',
                'verbose_name_plural': 'الاختيارات (الإجابات)',
            },
        ),
        migrations.CreateModel(
            name='StudentTaskRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_on', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_records', to='internest_core.studentprofile')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='internest_core.gamificationtask')),
            ],
            options={
                'verbose_name': 'سجل إكمال مهمة',
                'verbose_name_plural': 'سجلات إكمال المهام',
                'unique_together': {('student', 'task')},
            },
        ),
    ]
