# Generated by Django 5.2.7 on 2025-11-10 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internest_core', '0005_gamificationtask_taskquestion_taskanswer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='الكود')),
                ('discount_percentage', models.PositiveIntegerField(help_text='رقم من 1 إلى 100', verbose_name='نسبة الخصم (%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال؟')),
            ],
            options={
                'verbose_name': 'كود خصم',
                'verbose_name_plural': '🏷️ أكواد الخصم',
            },
        ),
        migrations.CreateModel(
            name='StudentEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_on', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التسجيل')),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='السعر المدفوع')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='internest_core.partnercoursesubmission', verbose_name='الكورس')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_courses', to='internest_core.studentprofile', verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'تسجيل (كورس)',
                'verbose_name_plural': '🧑\u200d🎓 تسجيلات الطلاب في الكورسات',
                'unique_together': {('student', 'course')},
            },
        ),
    ]
