# Generated by Django 5.2.7 on 2026-10-08 16:54

import django.core.validators
import internest_core.models
from django.db import migrations, models


OLD_TO_NEW = {
    "قيد المراجعة": "submitted",      # pending (not yet forwarded)
    "محول للشريك": "under_review",    # forwarded to the startup
    "مرفوض": "fulfilled",             # declined → shown to students as "position filled"
}


def map_statuses(apps, schema_editor):
    Application = apps.get_model("internest_core", "Application")
    for old, new in OLD_TO_NEW.items():
        Application.objects.filter(status=old).update(status=new)


def unmap_statuses(apps, schema_editor):
    Application = apps.get_model("internest_core", "Application")
    for old, new in OLD_TO_NEW.items():
        Application.objects.filter(status=new).update(status=old)
    Application.objects.filter(status="accepted").update(status="محول للشريك")


class Migration(migrations.Migration):

    dependencies = [
        ('internest_core', '0005_email_verification'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='emailverification',
            new_name='internest_c_user_id_5b72d0_idx',
            old_name='intnst_evrf_user_type_verified_idx',
        ),
        migrations.RenameIndex(
            model_name='emailverification',
            new_name='internest_c_code_474897_idx',
            old_name='intnst_evrf_code_idx',
        ),
        migrations.AddField(
            model_name='application',
            name='decided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under review'), ('accepted', 'Accepted'), ('fulfilled', 'Position filled')], default='submitted', max_length=50),
        ),
        migrations.AlterField(
            model_name='partnerprofile',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='partner_logos/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'svg']), internest_core.models.validate_max_file_size], verbose_name='شعار الشركة/الجهة'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='cv_file',
            field=models.FileField(blank=True, null=True, upload_to='cvs/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx']), internest_core.models.validate_max_file_size], verbose_name='ملف السيرة الذاتية (CV)'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), internest_core.models.validate_max_file_size], verbose_name='صورة الملف الشخصي'),
        ),
        migrations.RunPython(map_statuses, unmap_statuses),
    ]
