# Generated by Django 5.2.7 on 2026-10-09 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internest_core', '0007_ensure_application_review_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='contact_consent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='shortlisted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='bio',
            field=models.TextField(blank=True, default='', max_length=600, verbose_name='About me & projects'),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under review'), ('shortlisted', 'Shortlisted for interview'), ('accepted', 'Accepted'), ('fulfilled', 'Position filled')], default='submitted', max_length=50),
        ),
    ]
