# Generated by Django 5.2.7 on 2026-10-09 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internest_core', '0008_shortlist_funnel'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='talent_pool_visible',
            field=models.BooleanField(default=False, verbose_name='Show me in the Talent Pool'),
        ),
    ]
