# Generated by Django 5.2.7 on 2026-10-09 17:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internest_core', '0009_talent_pool_opt_in'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='talent_pool_visible',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Show me in the Talent Pool'),
        ),
        migrations.AddIndex(
            model_name='studentprofile',
            index=models.Index(condition=models.Q(('talent_pool_visible', True)), fields=['university'], name='student_pool_university_idx'),
        ),
        migrations.AddIndex(
            model_name='studentprofile',
            index=models.Index(condition=models.Q(('talent_pool_visible', True)), fields=['major'], name='student_pool_major_idx'),
        ),
    ]
