# Generated by Django 5.2.7 on 2026-10-09 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internest_core', '0010_talent_pool_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='source',
            field=models.CharField(choices=[('direct', 'Direct'), ('invited', 'Invited')], default='direct', max_length=10),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='portfolio_url',
            field=models.URLField(blank=True, default='', verbose_name='Portfolio link'),
        ),
    ]
