# Generated by Django 5.2.7 on 2026-10-10 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internest_core', '0011_application_source_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerprofile',
            name='country_of_registration',
            field=models.CharField(blank=True, default='', max_length=2, verbose_name='Country of registration'),
        ),
    ]
